name: common_template_for_lamm
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  library_architecture_mvvm_modify: ^0.1.2
  meta: ^1.8.0

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.1